baseurl = "http://www.ourpromises.io"
title = "Our Promises"
theme = "dimension"
publishDir = "/opt/build"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Our Promises"
  description = '<!--[-->To use technology and media to create simple solutions and promote new, creative ideas in communities everywhere. <!--]--><br />Work to help inspire, inform, and educate young people and those in need. <!--]--><br />THAT’S OUR PROMISE.
                <!--[--></a> <!--]-->'
  logo = "fa-diamond"
  copyright = "OurPromisesIO"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Our Promises"

