version: '3'
services:
  app:
    image:  publysher/hugo
    # env_file: .env
    volumes:
      - ./code/src:/opt/src
      - .:/opt/build
    working_dir: /opt/src
    ports: 
      - 1313:1313
    command: hugo server --bind=0.0.0.0
    environment:
      HUGO_BASE_URL: "http://www.ourpromises.io"
